### ISSUE TITLE
Add this you dumb

### ISSUE THREAD

**Issue by onyxiarivera** [onyxcode/sps#1]
```
def startup():
	print("Starting...")
	
	if not os.path.exists("password.txt"):
	   print("Setting up...")
	   f = open("password.txt", "w")
        with f:
           f.write(input("Please set a passoword: \n"))
	   f.close
     	   pass
  	   menu()
    
	else:
	   menu()
```

Fix the indents when you're not on a ___phone___

**Comment by timanttikuutio** [comment]
Merge `f = open("password.txt", "w")
        with f:`

To `with open("passwords.txt", "w") as f: ...`
Doing that will also autoclose the file after ur done so no need to `f.close()` :)

**Comment by onyxiarivera** [comment]
# Thing added to the file
___yes___
